version: '2'
services:
    matv52-app:
        image: matv52
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://matv52-postgresql:5432/matv52
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    matv52-postgresql:
        extends:
            file: postgresql.yml
            service: matv52-postgresql
