version: '2'
services:
    matv52-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/matv52/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=matv52
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
